#!/bin/bash

if [ $# -ne 2 ]; then
    echo "$0: usage is:"
    echo "$0 <debian_version> <glmark2_tag>"
    echo "debian_version: Debian base Docker image tag (https://hub.docker.com/_/debian/tags)"
    echo "example: gh_build 10.13 2021.02"
    exit 1
fi

DEBIAN_VERSION="$1"
GLMARK2_TAG="$2"

gh workflow run build-image \
   -F debian_version="${DEBIAN_VERSION}" \
   -F glmark2_tag="${GLMARK2_TAG}"
