name: docker-build-image

on:
  workflow_dispatch:
    inputs:
      debian_version:
        description: 'Debian version (e.g., buster, bullseye)'
        default: 'buster'
      glmark2_tag:
        description: 'glmark2 Git tag'
        default: '2021.02'

env:
  IMAGENAME: "debian-glmark2"
  DEBIAN_VERSION: ${{ github.event.inputs.debian_version || vars.DEBIAN_VERSION }}
  GLMARK2_REPO: 'https://github.com/glmark2/glmark2.git'
  GLMARK2_TAG: ${{ github.event.inputs.glmark2_tag || vars.GLMARK2_TAG }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set version value
        id: version
        run: |
          echo "value=${GLMARK2_TAG}.${DEBIAN_VERSION}.$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:context"
          build-args: |
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
            GLMARK2_REPO=${{ env.GLMARK2_REPO }}
            GLMARK2_TAG=${{ env.GLMARK2_TAG }}
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
            debian-glmark2:latest
      - name: Create self-contained glmark2 package
        run: |
          mkdir glmark2-package
          docker create --name glmark2-container debian-glmark2:latest
          docker cp glmark2-container:/opt/glmark2 glmark2-package/glmark2
          docker rm glmark2-container
          tar -czf glmark2-${{ steps.version.outputs.value }}.tar.gz -C glmark2-package glmark2
      - name: Create Release with Self-Contained Package
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.version.outputs.value }}"
          name: "glmark2 ${{ steps.version.outputs.value }}"
          body: |
            Self-contained glmark2 package for tag ${{ env.GLMARK2_TAG }} on Debian ${{ env.DEBIAN_VERSION }}.
            To run:
            1. Extract the archive: `tar -xzf glmark2-${{ steps.version.outputs.value }}.tar.gz`
            2. Run: `./glmark2/bin/glmark2 --fullscreen`
          files: glmark2-${{ steps.version.outputs.value }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
