name: docker-build-image

on:
  workflow_dispatch:
    inputs:
      debian_version:
        description: 'Debian version (e.g., buster, bullseye)'
        default: 'buster'
      glmark2_tag:
        description: 'glmark2 Git tag'
        default: '2021.02'

env:
  IMAGENAME: "debian-glmark2"
  DEBIAN_VERSION: ${{ github.event.inputs.debian_version || vars.DEBIAN_VERSION }}
  GLMARK2_REPO: 'https://github.com/glmark2/glmark2.git'
  GLMARK2_TAG: ${{ github.event.inputs.glmark2_tag || vars.GLMARK2_TAG }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set version value
        id: version
        run: |
          echo "value=${DEBIAN_VERSION}.${GLMARK2_TAG}.$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:context"
          build-args: |
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
            GLMARK2_REPO=${{ env.GLMARK2_REPO }}
            GLMARK2_TAG=${{ env.GLMARK2_TAG }}
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
